import { getConversations } from "../actions/getConversations";
import SideBar from "../components/sidebar/Sidebar";
import { PingList } from "./components/PingList";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const userConversations = await getConversations();
  return (
    // @ts-expect-error Server Component
    <SideBar>
      <PingList conversations={userConversations} />
      {children}
    </SideBar>
  );
}
