import SideBar from "../components/sidebar/Sidebar";
import { PingBox } from "./components/PingBox";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // @ts-expect-error Server Component
    <SideBar>
      <PingBox />
      {children}
    </SideBar>
  );
}
