import "../globals.css";
import { Inter } from "next/font/google";
import { AuthContext } from "../context/AuthContext";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`max-w-[117rem] mx-auto ${inter.className}`}>
        <AuthContext>{children}</AuthContext>
      </body>
    </html>
  );
}
