import { Inter } from "next/font/google";

import { AuthContext } from "./context/AuthContext";
import { ToastContext } from "./context/ToastContext";

import QueryProvider from "./utils/QueryProvider";

import "./globals.css";
import { NextThemeProvider } from "./providers/ThemeProvider";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`max-w-[117rem] mx-auto ${inter.className} dark:bg-black`}
      >
        <AuthContext>
          <ToastContext />
          <QueryProvider>
            <NextThemeProvider>{children}</NextThemeProvider>
          </QueryProvider>
        </AuthContext>
      </body>
    </html>
  );
}
